### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by aaniceto** [DadUndead/ngx-scorm-wrapper#1]
Hi,

Very new to this SCORM thingy..

I've installed the module.. and imported on my .module.ts file
_import { ScormWrapperModule, ScormWrapperService } from 'ngx-scorm-wrapper';_

also passed the module to the imports and the service to the providers..

I have a scorm package to test.. how should this work exactly?

Sorry for the very basic question but the documentation in thin.

**Comment by ghost** [comment]
You can use the ScormWrapperService in any of your components (after you added it to the providers in your app.module). Just add the service to your component class constructor like:

`constructor(private sws: ScormWrapperService)`

You can now use the methods found here: https://github.com/patamechanix/angularjs-scorm-wrapper

**Comment by DadUndead** [comment]
> You can use the ScormWrapperService in any of your components (after you added it to the providers in your app.module). Just add the service to your component class constructor like:
> 
> `constructor(private sws: ScormWrapperService)`
> 
> You can now use the methods found here: https://github.com/patamechanix/angularjs-scorm-wrapper

Thanks for your help! I updated readme.md
